educate/accounts/urls.py
from django.urls import path
from django.conf.urls import url
#from django.contrib.auth import login
from django.contrib.auth.views import login, logout
from .views.tech_leader import views
from .views.tutor_leader import views as tutor_leader
from .views.tech import views as tech
from .views.tutor import views as tutor

app_name = 'accounts'

urlpatterns = [
    ############################# LOGIN REDIRECT ###############################
    path('', views.LoginRedirect, name='login_redirect'),
    path('login/', login, {'template_name': 'accounts/login.html'}, name='login'),
    path('logout/', logout, name='logout'),
    ############################# TECH_LEADER (t) ##############################
    # Users
    path('t/users/create', views.UserCreate.as_view(), name='user_create'),
    path('t/users/', views.UserList.as_view(), name='user_list'),
    path('t/users/update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('t/users/delete/<int:pk>/', views.UserDelete.as_view(), name='user_delete'),
    path('t/users/show/<int:pk>/', views.UserShow.as_view(), name='user_show'),
    # Sector
    path('t/sectors/create', views.SectorCreate.as_view(), name='sector_create'),
    path('t/sectors/', views.SectorList.as_view(), name='sector_list'),
    path('t/sectors/update/<int:pk>/', views.SectorUpdate.as_view(), name='sector_update'),
    path('t/sectors/delete/<int:pk>/', views.SectorDelete.as_view(), name='sector_delete'),
    path('t/sectors/show/<int:pk>/', views.SectorShow.as_view(), name='sector_show'),
    # Schools
    path('t/schools/', views.SchoolList.as_view(), name='school_list'),
    path('t/schools/create', views.SchoolCreate.as_view(), name='school_create'),
    path('t/schools/update/<int:pk>/', views.SchoolUpdate.as_view(), name='school_update'),
    path('t/schools/delete/<int:pk>/', views.SchoolDelete.as_view(), name='school_delete'),
    path('t/schools/show/<int:pk>/', views.SchoolShow.as_view(), name='school_show'),
    # Visit
    path('t/visits/', views.VisitList.as_view(), name='visit_list'),
    path('t/visits/create', views.VisitCreate.as_view(), name='visit_create'),
    path('t/visits/update/<int:pk>/', views.VisitUpdate.as_view(), name='visit_update'),
    path('t/visits/delete/<int:pk>/', views.VisitDelete.as_view(), name='visit_delete'),
    path('t/visits/show/<int:pk>/', views.VisitShow.as_view(), name='visit_show'),
    # Requeriment
    path('t/requirements/', views.RequirementList.as_view(), name='requirement_list'),
    path('t/requirements/create', views.RequirementCreate.as_view(), name='requirement_create'),
    path('t/requirements/update/<int:pk>/', views.RequirementUpdate.as_view(), name='requirement_update'),
    path('t/requirements/delete/<int:pk>/', views.RequirementDelete.as_view(), name='requirement_delete'),
    path('t/requirements/show/<int:pk>/', views.RequirementShow.as_view(), name='requirement_show'),
    ############################# TUTOR_LEADER (r) #############################
    # Planning
    path('r/planning/', tutor_leader.PlanningList.as_view(), name='planning_list'),
    path('r/planning/create/requirement', tutor_leader.PlanningCreate.as_view(), name='planning_requirement_create'),
    path('r/planning/create/visit', tutor_leader.VisitCreate.as_view(), name='planning_visit_create'),
    path('r/planning/show/<int:pk>/', tutor_leader.VisitShow.as_view(), name='planning_show'),
    path('r/planning/update/requirement/<int:pk>/', tutor_leader.PlanningUpdate.as_view(), name='planning_requirement_update'),
    path('r/planning/update/visit/<int:pk>/', tutor_leader.VisitUpdate.as_view(), name='planning_visit_update'),
    path('r/planning/delete/<int:pk>/', tutor_leader.VisitDelete.as_view(), name='planning_delete'),
    # AJAX
    url(r'^r/planning/ajax/$', tutor_leader.ItemUpdate, name='planning_item_update'),
    # Visit
    path('r/visits/', tutor_leader.VisitList.as_view(), name='visit_list_tutor_leader'),
    path('r/visits/show/<int:pk>/', tutor_leader.VisitDetail.as_view(), name='visit_show_tutor_leader'),
    # Requeriment
    path('r/requirements/', tutor_leader.RequirementList.as_view(), name='requirement_list_tutor_leader'),
    path('r/requirements/create', tutor_leader.RequirementCreate.as_view(), name='requirement_create_tutor_leader'),
    path('r/requirements/update/<int:pk>/', tutor_leader.RequirementUpdate.as_view(), name='requirement_update_tutor_leader'),
    path('r/requirements/delete/<int:pk>/', tutor_leader.RequirementDelete.as_view(), name='requirement_delete_tutor_leader'),
    path('r/requirements/show/<int:pk>/', tutor_leader.RequirementShow.as_view(), name='requirement_show_tutor_leader'),
    ############################# TUTOR (nr) ###################################
    # Planning
    path('nr/planning/', tutor.PlanningList.as_view(), name='planning_list_tutor'),
    path('nr/planning/create/requirement', tutor.PlanningCreate.as_view(), name='planning_requirement_create_tutor'),
    path('nr/planning/create/visit', tutor.VisitCreate.as_view(), name='planning_visit_create_tutor'),
    path('nr/planning/show/<int:pk>/', tutor.VisitShow.as_view(), name='planning_show_tutor'),
    path('nr/planning/update/requirement/<int:pk>/', tutor.PlanningUpdate.as_view(), name='planning_requirement_update_tutor'),
    path('nr/planning/update/visit/<int:pk>/', tutor.VisitUpdate.as_view(), name='planning_visit_update_tutor'),
    path('nr/planning/delete/<int:pk>/', tutor.VisitDelete.as_view(), name='planning_delete_tutor'),
    # AJAX
    url(r'^nr/planning/ajax/$', tutor.ItemUpdate, name='planning_item_update_tutor'),
    # Requeriment
    path('nr/requirements/', tutor.RequirementList.as_view(), name='requirement_list_tutor'),
    path('nr/requirements/create', tutor.RequirementCreate.as_view(), name='requirement_create_tutor'),
    path('nr/requirements/update/<int:pk>/', tutor.RequirementUpdate.as_view(), name='requirement_update_tutor'),
    path('nr/requirements/delete/<int:pk>/', tutor.RequirementDelete.as_view(), name='requirement_delete_tutor'),
    path('nr/requirements/show/<int:pk>/', tutor.RequirementShow.as_view(), name='requirement_show_tutor'),
    ############################# TECH (nt) ####################################
    # Planning
    path('nt/planning/', tech.PlanningList.as_view(), name='planning_list_tech'),
    path('nt/planning/show/<int:pk>/', tech.VisitShow.as_view(), name='planning_show_tech'),
    # AJAX
    url(r'^nt/planning/ajax/$', tech.ItemUpdate, name='planning_item_update_tech'),
]

educate/educate/urls.py
from django.contrib import admin
from django.urls import path #, include
from educate import views

### SERVICEWEB
from django.conf.urls import url, include

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    ### PASSWORD RESET
    #path('', include(('password_reset.urls', 'password_reset'), namespace='password_reset')),
    path('', include('password_reset.urls')),
    #url(r'recover/', include('password_reset.urls')),

    ### SERVICEWEB
    url(r'serviceweb/', include('serviceweb.urls')),
]

educate/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db import connection
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, TemplateView
from django.views.generic.detail import DetailView

from . models import User, School, Requirement, Visit
from .forms import UserForm, SchoolForm, RequirementForm, VisitForm
from . decorators import tech_leader_required

@login_required
def LoginRedirect(request):
    user = request.user
    args = {'test': user}
    if user.user_type == 1: # tutor
        return render(request, 'tutor/home.html', args)
    elif user.user_type == 2: # tech
        return render(request, 'tech/home.html', args)
    elif user.user_type == 3: # tutor_leader
        return render(request, 'tutor_leader/home.html', args)
    elif user.user_type == 4: # tech_leader
        return render(request, 'tech_leader/home.html', args)

##############################    Users    #####################################

@method_decorator([login_required, tech_leader_required], name='dispatch')
class UserCreate(CreateView):
    model = User
    template_name = 'tech_leader/user/form.html'
    form_class = UserForm
    success_url = reverse_lazy('accounts:user_list')

@method_decorator([login_required, tech_leader_required], name='dispatch')
class UserList(ListView):
    queryset = User.objects.order_by('id')
    template_name = 'tech_leader/user/list.html'

@method_decorator([login_required, tech_leader_required], name='dispatch')
class UserUpdate(UpdateView):
    model = User
    form_class = UserForm
    template_name = 'tech_leader/user/form.html'
    success_url = reverse_lazy('accounts:user_list')

@method_decorator([login_required, tech_leader_required], name='dispatch')
class UserDelete(DeleteView):
    model = User
    template_name = 'tech_leader/user/delete.html'
    success_url = reverse_lazy('accounts:user_list')

@method_decorator([login_required, tech_leader_required], name='dispatch')
class UserShow(DetailView):
    model = User
    template_name = 'tech_leader/user/show.html'

##############################    School    ####################################

@method_decorator([login_required, tech_leader_required], name='dispatch')
class SchoolCreate(CreateView):
    model = School
    template_name = 'tech_leader/school/form.html'
    form_class = SchoolForm
    success_url = reverse_lazy('accounts:school_list')
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super(SchoolCreate, self).form_valid(form)

@method_decorator([login_required, tech_leader_required], name='dispatch')
class SchoolList(ListView):
    queryset = School.objects.order_by('id')
    template_name = 'tech_leader/school/list.html'

@method_decorator([login_required, tech_leader_required], name='dispatch')
class SchoolUpdate(UpdateView):
    model = School
    form_class = SchoolForm
    template_name = 'tech_leader/school/form.html'
    success_url = reverse_lazy('accounts:school_list')

@method_decorator([login_required, tech_leader_required], name='dispatch')
class SchoolDelete(DeleteView):
    model = School
    template_name = 'tech_leader/school/delete.html'
    success_url = reverse_lazy('accounts:school_list')

@method_decorator([login_required, tech_leader_required], name='dispatch')
class SchoolShow(DetailView):
    model = School
    template_name = 'tech_leader/school/show.html'

##############################    Visit    #####################################
@method_decorator([login_required, tech_leader_required], name='dispatch')
class VisitCreate(CreateView):
    model = Visit
    template_name = 'tech_leader/visit/form.html'
    form_class = VisitForm
    success_url = reverse_lazy('accounts:visit_list')

@method_decorator([login_required, tech_leader_required], name='dispatch')
class VisitList(TemplateView):
    template_name = 'tech_leader/visit/list.html'

    def get_context_data(self, **kwargs):
        context = super(VisitList, self).get_context_data(**kwargs)
        context['object_list'] = Visit.objects.order_by('id')
        context['object_requirement'] = Requirement.objects.all()
        context['object_school'] = School.objects.all()
        return context

@method_decorator([login_required, tech_leader_required], name='dispatch')
class VisitUpdate(UpdateView):
    model = Visit
    form_class = VisitForm
    template_name = 'tech_leader/visit/form.html'
    success_url = reverse_lazy('accounts:visit_list')

@method_decorator([login_required, tech_leader_required], name='dispatch')
class VisitDelete(DeleteView):
    model = Visit
    template_name = 'tech_leader/visit/delete.html'
    success_url = reverse_lazy('accounts:visit_list')

@method_decorator([login_required, tech_leader_required], name='dispatch')
class VisitShow(DetailView):
    model = Visit
    template_name = 'tech_leader/visit/show.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(VisitShow, self).get_context_data(**kwargs)
        # Add extra context from another model
        context['object_requirement'] = Requirement.objects.all()
        context['object_school'] = School.objects.all()
        return context

#############################  Requirement  ####################################

@method_decorator([login_required, tech_leader_required], name='dispatch')
class RequirementCreate(CreateView):
    model = Requirement
    template_name = 'tech_leader/requirement/form.html'
    form_class = RequirementForm
    success_url = reverse_lazy('accounts:requirement_list')
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.user_id = self.request.user.id
        return super(RequirementCreate, self).form_valid(form)

@method_decorator([login_required, tech_leader_required], name='dispatch')
class RequirementList(ListView):
    queryset = Requirement.objects.order_by('id')
    template_name = 'tech_leader/requirement/list.html'

@method_decorator([login_required, tech_leader_required], name='dispatch')
class RequirementUpdate(UpdateView):
    model = Requirement
    form_class = RequirementForm
    template_name = 'tech_leader/requirement/form.html'
    success_url = reverse_lazy('accounts:requirement_list')

@method_decorator([login_required, tech_leader_required], name='dispatch')
class RequirementDelete(DeleteView):
    model = Requirement
    template_name = 'tech_leader/requirement/delete.html'
    success_url = reverse_lazy('accounts:requirement_list')

@method_decorator([login_required, tech_leader_required], name='dispatch')
class RequirementShow(DetailView):
    model = Requirement
    template_name = 'tech_leader/requirement/show.html'

educate/accounts/views/tech/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db import connection
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, TemplateView
from django.views.generic.detail import DetailView
from django.db.models import Q
from datetime import datetime

from ... models import User, School, Requirement, Visit, TechnicalForm, PedagogicalForm
from ... forms import UserForm, SchoolForm, RequirementForm, VisitForm
from ... decorators import tech_required

@login_required
def LoginRedirect(request):
    user = request.user
    args = {'test': user}
    if user.user_type == 1: # tutor
        return HttpResponseRedirect('/accounts/nr/planning/')
    elif user.user_type == 2: # tech
        return HttpResponseRedirect('/accounts/nt/planning/')
    elif user.user_type == 3: # tutor_leader
        return HttpResponseRedirect('/accounts/r/planning/')
    elif user.user_type == 4: # tech_leader
        return HttpResponseRedirect('/accounts/t/users/')

##############################    Visit    #####################################

@method_decorator([login_required, tech_required], name='dispatch')
class VisitShow(DetailView):
    model = Visit
    template_name = 'tech/planning/show.html'

    def get_context_data(self, **kwargs):
        context = super(VisitShow, self).get_context_data(**kwargs)
        try:
            #obtener información de los formularios
            context['object_technical_form'] = TechnicalForm.objects.filter(Q(visit=self.kwargs['pk']))
            context['object_pedagogical_form'] = PedagogicalForm.objects.filter(Q(visit=self.kwargs['pk']))
            print(context['object_pedagogical_form'])
        except TechnicalForm.DoesNotExist:
            context['object_technical_form'] = None
        except  PedagogicalForm.DoesNotExist:
            context['object_pedagogical_form'] = None
        return context

############################    Planning    ####################################

@method_decorator([login_required, tech_required], name='dispatch')
class PlanningList(TemplateView):
    template_name = 'tech/planning/list.html'

    def get_context_data(self, **kwargs):
        context = super(PlanningList, self).get_context_data(**kwargs)
        date_planned = datetime.now()
        date_planned = date_planned.strftime("%Y-%m-%d")
        try:
            context['object_visit'] = Visit.objects.filter(Q(user=self.request.user) & Q(date_planned__contains=date_planned)).order_by('date_planned')
            query_set = Visit.objects.filter(Q(user=self.request.user)).order_by('date_planned')
            data = []
            for visit in query_set:
                data.append(str(visit.date_planned.date()))
            context['data'] = list(set(data))
            print(list(set(data)))
        except Visit.DoesNotExist:
            context['object_visit'] = None
            context['data'] = None
        return context

@login_required
def ItemUpdate(request):
    try:
        query_set = Visit.objects.filter(Q(user=request.user) & Q(date_planned__contains=request.GET.get('date_planned'))).order_by('date_planned')
    except Visit.DoesNotExist:
        query_set = None
    return render(request, 'tech/planning/items.html', {'object_visit':query_set})

educate/accounts/templates/tech_leader/school/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Fundación E-dúdacte -->
    <link rel="shortcut icon" href="http://educate.org.ec/wp-content/uploads/2018/01/favicon-2018.png">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- DataTables Responsive -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap.min.css">
    <!-- Font Stylesheet-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli">
    {% load static %}
    {% block head %}
    <link rel="stylesheet" href="{% static 'accounts/css/style.css' %}" type="text/css">
    {% endblock %}
    <title>Fundacion Educate</title>
  </head>
  <body>
    {% block body %}
    <!-- SidebarNavigation -->
    <nav class="navbar navbar-inverse sidebarNavigation" data-sidebarClass="navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle left-navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'accounts:login_redirect' %}">Control de Visitas</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'accounts:user_list' %}">Usuarios</a></li>
            <li><a href="{% url 'accounts:sector_list' %}">Sectores</a></li>
            <li class="active"><a href="{% url 'accounts:school_list' %}">Escuelas</a></li>
            <li><a href="{% url 'accounts:visit_list' %}">Visitas</a></li>
            <li><a href="{% url 'accounts:requirement_list' %}">Requerimientos</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><span class="glyphicon glyphicon-user"></span> &nbsp {{ request.user.first_name }} {{ request.user.last_name }}</a></li>
            <li><a href="{% url 'accounts:logout' %}"><span class="glyphicon glyphicon-log-out"></span> &nbsp Cerrar Sesión</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      {% block content %}
      <!-- Here goes your page content -->
      {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="{% static 'accounts/js/validateSchool.js' %}"></script>
    <script src="{% static 'accounts/js/script.js' %}"></script>
    <script src="{% static 'accounts/js/sidebarNavigation.js' %}"></script>
    {% endblock %}
  </body>
</html>

educate/accounts/templates/tech_leader/school/delete.html
{% extends 'tech_leader/school/base.html' %}

{% block content %}

<div class="section-title">
  <a class="btn btn-default" href="{{request.META.HTTP_REFERER|escape }}"><span class='glyphicon glyphicon-chevron-left'></span>&nbsp Atrás</a>
  <hr>
</div>

<form method="post">
  {% csrf_token %}
  <p><strong>¿Quieres eliminar esta escuela?</strong></p>
  <p>{{ object.name }}</p>
  <p>Si eliminas este registro, no podrás recuperarlo.</p>
  <hr>
  <button class="btn btn-danger" type="submit"><span class='glyphicon glyphicon-trash'></span>&nbsp Eliminar</button>
  <a class="btn btn-default" href="{{request.META.HTTP_REFERER|escape }}"><span class='glyphicon glyphicon-remove'></span>&nbsp Cancelar</a>
</form>
{% endblock%}

educate/accounts/templates/tech_leader/school/form.html
{% extends 'tech_leader/school/base.html' %}

{% block content %}

<div class="section-title">
  <a class="btn btn-default" href="{{request.META.HTTP_REFERER|escape }}"><span class='glyphicon glyphicon-chevron-left'></span>&nbsp Atrás</a>
  <hr>
</div>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <hr>
  <button class="btn btn-success" type="submit"><span class='glyphicon glyphicon-floppy-saved'></span>&nbsp Guardar</button>
</form>
{% endblock%}

educate/accounts/templates/tech_leader/school/list.html
{% extends 'tech_leader/school/base.html' %}

{% block content %}
<div class="section-title">
  <a class="btn btn-success" href="{% url 'accounts:school_create' %}"><span class='glyphicon glyphicon-plus-sign'></span>&nbsp Nueva Escuela </a>
  <hr>
</div>

{% if object_list %}
<table class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%" id="my-table">
  <thead>
    <tr>
      <td>AMIE</td>
      <td>Nombre</td>
      <!--<td>Teléfono</td>-->
      <td>Dirección</td>
      <!--<td>Referencia</td>-->
      <!--<td>Parroquia</td>-->
      <td>Prioridad</td>
      <!--<td>Fecha de creación</td>-->
      <!--<td>Creado por</td>-->
      <!--<td>Sector</td>-->
      <!--<td>Embajador IN</td>-->
      <td>Jornada</td>
      <td>Acciones</td>
    </tr>
  </thead>
  <tbody>
    <tr>
      {% for school in object_list %}
      <td>{{ school.amie }}</td>
      <td>{{ school.name }}</td>
      <!--<td>{{ school.phone_number }}</td>-->
      <td>{{ school.address }}</td>
      <!--<td>{{ school.reference }}</td>-->
      <!--<td>{{ school.parish }}</td>-->
      <td>
        {% if school.priority == 1 %}
        No
        {% else %}
        Si
        {% endif %}
      </td>
      <!--<td>{{ school.date_joined }}</td>-->
      <!--<td>{{ school.created_by }}</td>-->
      <td>
        {% if school.workday == 1 %}
        Matutina
        {% elif school.workday == 2 %}
        Vespertina
        {% else %}
        Matutina/Vespertina
        {% endif %}
      </td>
      <td>
        <a class="btn btn-success" href="{% url 'accounts:school_show' school.id %}"><span class='glyphicon glyphicon-eye-open'></span></a>
        <a class="btn btn-primary" href="{% url 'accounts:school_update' school.id %}"><span class='glyphicon glyphicon-edit'></span></a>
        <a class="btn btn-danger" href="{% url 'accounts:school_delete' school.id %}"><span class='glyphicon glyphicon-trash'></span></a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<h3>No hay registros que mostrar</h3>
{% endif %}

{% endblock%}

educate/accounts/templates/tech_leader/school/show.html
{% extends 'tech_leader/school/base.html' %}

{% block content %}

<div class="section-title">
  <a class="btn btn-default" href="{% url 'accounts:school_list' %}"><span class='glyphicon glyphicon-chevron-left'></span>&nbsp Atrás</a>
  <a class="btn btn-primary" href="{% url 'accounts:school_update' object.id %}"><span class='glyphicon glyphicon-edit'></span>&nbsp Editar</a>
  <a class="btn btn-danger" href="{% url 'accounts:school_delete' object.id %}"><span class='glyphicon glyphicon-trash'></span>&nbsp Eliminar</a>
  <hr>
</div>

<h3 class="header">Información General</h3>
<p><strong>AMIE: </strong>{{ object.amie }}</p>
<p><strong>Nombre: </strong>{{ object.name }}</p>
<p><strong>Teléfono: </strong>{{ object.phone_number }}</p>
<p><strong>Dirección: </strong>{{ object.address }}</p>
<p><strong>Referencia: </strong>{{ object.reference }}</p>
<p><strong>Parroquia: </strong>{{ object.parish }}</p>
<p>
  <strong>Prioridad: </strong>
  {% if object.priority == 1 %}
  No
  {% else %}
  Si
  {% endif %}
</p>
<p><strong>Sector: </strong>{{ object.sector }}</p>
<p>
  <strong>Estado: </strong>
  {% if object.is_active == True %}
  Activo
  {% else %}
  Inactivo
  {% endif %}
</p>
<p><strong>Embajador IN: </strong>{{ object.ambassador_in }}</p>
<p>
  <strong>Jornada: </strong>
  {% if object.workday == 1 %}
  Matutina
  {% elif object.workday == 2 %}
  Vespertina
  {% else %}
  Matutina/Vespertina
  {% endif %}
</p>
<hr>

<h3 class="header">Registro de actividad</h3>
<p><strong>Creado por: </strong>{{ object.created_by }}</p>
<p><strong>Fecha de creación: </strong>{{ object.date_joined }}</p>
{% if object.updated_by == None %}
<!--No hay información-->
{% else %}
<p><strong>Modificado por: </strong>{{ object.updated_by }}</p>
<p><strong>Fecha de modificación: </strong>{{ object.date_updated }}</p>
{% endif %}
<hr>
{% endblock%}